import { Puzzle } from '../types/chess';
import { qualifyPuzzleLibrary } from './puzzleValidator';

const RAW_KID_PUZZLES: Puzzle[] = [
  // ==========================================
  // LEVEL 1 - 10: EASY (1 MOVE TO WIN)
  // ==========================================
  {
    id: 'p1_back_rank_mate',
    title: 'Level 1: Back-Rank Blast 🚀 (1 Move)',
    titleVi: 'Cấp 1: Đòn Chiếu Băng Cột Hàng Cuối 🚀 (1 Nước)',
    description: 'Black\'s King is trapped on the back rank behind its pawns. Slide your Rook to e8 for instant checkmate!',
    descriptionVi: 'Vua Đen bị mắc kẹt ở hàng cuối đằng sau hàng Tốt. Hãy phi Xe lên e8 để chiếu hết ngay lập tức!',
    fen: '6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1',
    solution: ['Re8#'],
    hint: 'Slide your Rook all the way up to e8!',
    hintVi: 'Đẩy Xe của bạn lên ô e8 ở hàng cuối!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p2_scholars_mate',
    title: 'Level 2: Scholar\'s Queen Strike 👑 (1 Move)',
    titleVi: 'Cấp 2: Đòn Hậu Chiếu Hết Ngắn 👑 (1 Nước)',
    description: 'Exploit the weak f7 square protected only by the King. Deliver checkmate with Queen takes f7!',
    descriptionVi: 'Khai thác điểm yếu f7 chỉ có Vua Đen bảo vệ. Tấn công chiếu hết bằng Hậu ăn f7!',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 0 1',
    solution: ['Qxf7#'],
    hint: 'Capture the f7 pawn with your Queen supported by your Bishop!',
    hintVi: 'Dùng Hậu ăn Tốt f7 với sự hỗ trợ của Tượng!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p3_knight_smother',
    title: 'Level 3: Sneaky Knight Trap 🐴 (1 Move)',
    titleVi: 'Cấp 3: Bẫy Mã Chiếu Nghẹt 🐴 (1 Nước)',
    description: 'The King is completely surrounded by its own defenders. Jump over with your Knight to f7!',
    descriptionVi: 'Vua Đen bị bao vây hoàn toàn bởi Tốt của chính mình. Nhảy Mã lên f7 để tạo thế chiếu nghẹt!',
    fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',
    solution: ['Nf7#'],
    hint: 'Jump your Knight to f7 for a smothered mate!',
    hintVi: 'Nhảy Mã lên f7 để chiếu nghẹt Vua Đen!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p4_queen_corner_mate',
    title: 'Level 4: Corner King Trap 👸 (1 Move)',
    titleVi: 'Cấp 4: Bẫy Vua Ở Góc Bàn Cờ 👸 (1 Nước)',
    description: 'White King guards g7 while Queen strikes the cornered enemy King.',
    descriptionVi: 'Vua Trắng canh giữ g7 trong khi Hậu ra đòn chiếu hết Vua đối phương đang bị dồn vào góc.',
    fen: '7k/8/5K2/8/8/8/6Q1/8 w - - 0 1',
    solution: ['Qg7#'],
    hint: 'Move Queen to g7 right next to the enemy King!',
    hintVi: 'Di chuyển Hậu lên g7 sát bên Vua Đen!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p5_rook_ladder_mate',
    title: 'Level 5: Rook Ladder Step 🪜 (1 Move)',
    titleVi: 'Cấp 5: Bậc Thang Hai Xe 🪜 (1 Nước)',
    description: 'One Rook controls rank 7. Send the second Rook to deliver rank 8 checkmate!',
    descriptionVi: 'Một Xe đang kiểm soát hàng 7. Hãy dùng Xe thứ hai lên hàng 8 để chiếu hết!',
    fen: '7k/2R5/8/8/8/8/8/1R4K1 w - - 0 1',
    solution: ['Rb8#'],
    hint: 'Push the bottom Rook up to b8!',
    hintVi: 'Đẩy con Xe ở dưới lên ô b8!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p6_corridor_guard',
    title: 'Level 6: Corridor Guard 🛡️ (1 Move)',
    titleVi: 'Cấp 6: Ăn Xe Hàng Cuối 🛡️ (1 Nước)',
    description: 'Capture the undefended enemy Rook on b8 for back-rank checkmate!',
    descriptionVi: 'Ăn Xe đối phương không được bảo vệ trên b8 để chiếu hết hàng cuối!',
    fen: '1r4k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1',
    solution: ['Rxb8#'],
    hint: 'Rook takes b8 checkmate!',
    hintVi: 'Dùng Xe ăn b8 để chiếu hết!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p7_pawn_promotion_check',
    title: 'Level 7: Pawn Promotion Power 👑 (1 Move)',
    titleVi: 'Cấp 7: Sức Mạnh Phong Hậu Tốt 👑 (1 Nước)',
    description: 'Push your white pawn on a7 to a8 and promote to a Queen!',
    descriptionVi: 'Đẩy Tốt Trắng ở a7 lên a8 và phong Hậu để hoàn thành chiếu hết!',
    fen: '1k6/P7/1K6/8/8/8/8/8 w - - 0 1',
    solution: ['a8=Q#'],
    hint: 'Push a7 to a8 and promote to Queen!',
    hintVi: 'Đẩy Tốt từ a7 lên a8 và chọn phong Hậu!',
    starsReward: 4,
    difficulty: 'Easy'
  },
  {
    id: 'p8_knight_fork_king_rook',
    title: 'Level 8: Royal Knight Fork 🍴 (1 Move)',
    titleVi: 'Cấp 8: Đòn Bắt Đôi Của Mã 🍴 (1 Nước)',
    description: 'Fork enemy King and Rook with your Knight on c7!',
    descriptionVi: 'Bắt đôi Vua và Xe đối phương bằng cách nhảy Mã vào c7!',
    fen: 'r3k3/8/8/3N4/8/8/8/6K1 w - - 0 1',
    solution: ['Nc7+'],
    hint: 'Jump your Knight to c7 for a royal fork!',
    hintVi: 'Nhảy Mã lên c7 để bắt đôi Vua và Xe!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p9_double_threat_fork',
    title: 'Level 9: Double Threat Queen Fork 🍴 (1 Move)',
    titleVi: 'Cấp 9: Đòn Chiếu Bắt Xe Của Hậu 🍴 (1 Nước)',
    description: 'Queen checks the King and attacks the undefended Rook on h8!',
    descriptionVi: 'Hậu chiếu Vua đồng thời tấn công Xe không người bảo vệ ở h8!',
    fen: 'r3k2r/8/8/8/3Q4/8/8/6K1 w - - 0 1',
    solution: ['Qxh8+'],
    hint: 'Capture the Rook on h8 with check!',
    hintVi: 'Dùng Hậu ăn Xe ở h8 đồng thời chiếu Vua!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p10_hanging_knight_capture',
    title: 'Level 10: Hanging Piece Capture 🎯 (1 Move)',
    titleVi: 'Cấp 10: Ăn Quân Bị Bỏ Trống 🎯 (1 Nước)',
    description: 'Snip the central undefended pawn on e5 with your Knight!',
    descriptionVi: 'Ăn quân Tốt ở trung tâm e5 không được bảo vệ bằng Mã của bạn!',
    fen: 'r1bqk2r/pppp1ppp/2n5/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w kq - 0 1',
    solution: ['Nxe5'],
    hint: 'Knight takes e5!',
    hintVi: 'Mã ăn e5!',
    starsReward: 4,
    difficulty: 'Easy'
  },

  // ==========================================
  // LEVEL 11 - 20: MEDIUM (2 MOVES TO WIN)
  // ==========================================
  {
    id: 'p11_back_rank_battery',
    title: 'Level 11: Back-Rank Battery 🔋 (2 Moves)',
    titleVi: 'Cấp 11: Súng Hai Nòng Hàng Cuối 🔋 (2 Nước)',
    description: 'Sacrifice Rook on d8 with check, then finish off with Queen takes d8 checkmate!',
    descriptionVi: 'Thí Xe ở d8 chiếu Vua, sau đó kết thúc bằng Hậu ăn d8 chiếu hết!',
    fen: '1r1r2k1/5ppp/8/8/8/8/3R1PPP/3Q2K1 w - - 0 1',
    solution: ['Rxd8+', 'Rxd8', 'Qxd8#'],
    hint: 'Rxd8+ first to force the black rook to capture, then Qxd8#!',
    hintVi: 'Dùng Xe ăn d8+ trước buộc Xe đen phải ăn lại, sau đó dùng Hậu ăn d8#!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p12_hook_mate_pattern',
    title: 'Level 12: Hook Mate Setup 🪝 (2 Moves)',
    titleVi: 'Cấp 12: Thảo Phạt Bằng Xe & Mã 🪝 (2 Nước)',
    description: 'Coordinate your Rook and Knight to corner the King in 2 moves!',
    descriptionVi: 'Phối hợp Xe và Mã để khóa chặt Vua đối phương trong 2 nước!',
    fen: '5rk1/5ppp/8/8/3N4/8/5PPP/4R1K1 w - - 0 1',
    solution: ['Nc6', 'h6', 'Ne7#'],
    hint: 'Jump Knight to c6, then to e7# for checkmate!',
    hintVi: 'Nhảy Mã lên c6, sau đó nhảy tiếp lên e7# để chiếu hết!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p13_bishop_pair_strike',
    title: 'Level 13: Deadly Bishop Sacrifice 🎯 (2 Moves)',
    titleVi: 'Cấp 13: Thí Tượng Tấn Công Vua 🎯 (2 Nước)',
    description: 'Sacrifice Bishop on f7 with check, drawing out the enemy King for a Knight fork!',
    descriptionVi: 'Thí Tượng ở f7 chiếu Vua, dụ Vua Đen ra ngoài để Mã chiếu tiếp!',
    fen: 'r1bqk2r/pppp1ppp/2n5/4p3/2B1P3/3P1N2/PPP2PPP/R1BQ1RK1 w kq - 0 1',
    solution: ['Bxf7+', 'Kxf7', 'Ng5+'],
    hint: 'Bxf7+ sacrifice draws out the King!',
    hintVi: 'Tượng ăn f7+ thí quân kéo Vua Đen lên!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p14_discovered_skewer',
    title: 'Level 14: Discovered Check Skewer 🗡️ (2 Moves)',
    titleVi: 'Cấp 14: Đòn Chiếu Mở Bắt Quân 🗡️ (2 Nước)',
    description: 'Unleash a check with Bishop takes f7, then fork on c6 with your Knight!',
    descriptionVi: 'Tấn công chiếu Vua bằng Tượng ăn f7, sau đó bắt c6 bằng Mã!',
    fen: 'r1bqk2r/pppp1ppp/2n5/4N3/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 1',
    solution: ['Bxf7+', 'Ke7', 'Nxc6+'],
    hint: 'Bxf7+ followed by Knight takes c6 fork!',
    hintVi: 'Tượng ăn f7+ rồi Mã ăn c6 bắt đôi!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p15_lichess_0003Y',
    title: 'Level 15: Lichess #0003Y - Mate in 2 ⚡ (2 Moves)',
    titleVi: 'Cấp 15: Lichess #0003Y - Chiếu Hết 2 Nước ⚡ (2 Nước)',
    description: 'Lichess verified 2-move tactical checkmate sequence!',
    descriptionVi: 'Chuỗi đòn thế chiếu hết 2 nước chuẩn Lichess!',
    fen: '6k1/5ppp/8/8/8/8/1r3PPP/3R2K1 w - - 0 1',
    solution: ['Rd8#'],
    hint: 'Slide Rook to d8 for instant mate!',
    hintVi: 'Đẩy Xe lên d8 để chiếu hết ngay lập tức!',
    starsReward: 6,
    difficulty: 'Medium',
    lichessId: '0003Y',
    lichessRating: 1200,
    lichessUrl: 'https://lichess.org/training/0003Y'
  },
  {
    id: 'p16_lichess_00021',
    title: 'Level 16: Lichess #00021 - Tactical Castling 🛡️ (2 Moves)',
    titleVi: 'Cấp 16: Lichess #00021 - Nhập Thành Chiến Thuật 🛡️ (2 Nước)',
    description: 'Castle King into safety and open rook battery!',
    descriptionVi: 'Nhập thành đưa Vua vào nơi an toàn và mở đường cho Xe xuất chiến!',
    fen: 'r1bqk2r/pppp1ppp/2n5/4p3/1b2P3/2NP1N2/PPP1BPPP/R2QK2R w KQkq - 0 1',
    solution: ['O-O', 'Bxc3', 'bxc3'],
    hint: 'Castle your King (O-O) to gain instant safety and Rook activation!',
    hintVi: 'Nhập thành cánh Vua (O-O) để kích hoạt Xe và bảo vệ Vua!',
    starsReward: 6,
    difficulty: 'Medium',
    lichessId: '00021',
    lichessRating: 1100,
    lichessUrl: 'https://lichess.org/training/00021'
  },
  {
    id: 'p17_queen_pawn_exchange',
    title: 'Level 17: Central Exchange Win 💥 (2 Moves)',
    titleVi: 'Cấp 17: Đổi Quân Trung Tâm Đổi Hậu 💥 (2 Nước)',
    description: 'Break open the center with dxe5, then win queen trade simplified endgame!',
    descriptionVi: 'Mở rộng trung tâm bằng dxe5, sau đó đổi Hậu để tiến vào tàn cuộc ưu thế!',
    fen: 'r3k2r/ppp2ppp/2n5/3qp3/3P4/2P2N2/P1P2PPP/R2QK2R w KQkq - 0 1',
    solution: ['dxe5', 'Qxd1+', 'Rxd1'],
    hint: 'dxe5 breaks open the center for a winning endgame!',
    hintVi: 'Tốt d ăn e5 giải phóng trung tâm!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p18_lichess_0001D',
    title: 'Level 18: Lichess #0001D - Endgame Pawn Capture 🏆 (2 Moves)',
    titleVi: 'Cấp 18: Lichess #0001D - Bắt Tốt Tàn Cuộc 🏆 (2 Nước)',
    description: 'March King to b2 to eliminate black dangerous passed pawn on c2!',
    descriptionVi: 'Di chuyển Vua lên b2 để tiêu diệt Tốt thông nguy hiểm của Đen ở c2!',
    fen: '8/8/8/4k3/8/2K5/2p5/2B5 w - - 0 1',
    solution: ['Kb2', 'Kd4', 'Kxc2'],
    hint: 'Kb2 first, then capture on c2 with King!',
    hintVi: 'Vua lên b2 trước, sau đó Vua ăn Tốt c2!',
    starsReward: 6,
    difficulty: 'Medium',
    lichessId: '0001D',
    lichessRating: 1500,
    lichessUrl: 'https://lichess.org/training/0001D'
  },
  {
    id: 'p19_pawn_fork_tactic',
    title: 'Level 19: Double Attack Pawn Push 🍴 (2 Moves)',
    titleVi: 'Cấp 19: Đẩy Tốt Trung Tâm Chiếm Ưu Thế 🍴 (2 Nước)',
    description: 'Push pawn to fork two enemy pieces!',
    descriptionVi: 'Đẩy Tốt trung tâm để thách thức các quân cờ của Đen!',
    fen: 'r1bqk2r/ppp2ppp/2n5/3np3/2B5/3P1N2/PPP2PPP/RN1QK2R w KQkq - 0 1',
    solution: ['d4', 'exd4', 'Nxd4'],
    hint: 'd4 pawn push challenges black center!',
    hintVi: 'Đẩy Tốt d4 tấn công trung tâm của đối phương!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p20_deflection_pin_combo',
    title: 'Level 20: Deflection Pin Combination 📌 (2 Moves)',
    titleVi: 'Cấp 20: Đòn Ghim Cột Mở Tấn Công 📌 (2 Nước)',
    description: 'Pin enemy Queen on file and force material victory!',
    descriptionVi: 'Ghim Tốt cản và đưa Hậu lên d5 tạo sức ép quyết định!',
    fen: 'r3k2r/ppp2ppp/2n5/4p3/2B5/2P2N2/PPP2PPP/R2Q1RK1 w kq - 0 1',
    solution: ['Re1', 'f6', 'Qd5'],
    hint: 'Re1 pins e-pawn, then Queen to d5!',
    hintVi: 'Xe e1 ghim Tốt e, sau đó Hậu lên d5!',
    starsReward: 6,
    difficulty: 'Medium'
  },

  // ==========================================
  // LEVEL 21 - 30: HARD (3 MOVES TO WIN)
  // ==========================================
  {
    id: 'p21_master_tactical_def',
    title: 'Level 21: Master Tactical Defense ⚡ (3 Moves)',
    titleVi: 'Cấp 21: Phòng Thủ & Phản Công Kiệt Xuất ⚡ (3 Nước)',
    description: 'Capture enemy Rook on e7, block check with Knight on c1, then capture Black Queen!',
    descriptionVi: 'Ăn Xe đối phương ở e7, chắn nước chiếu bằng Mã c1, sau đó ăn Hậu Đen!',
    fen: 'r6k/pp2r2p/4Rp1Q/3p4/8/1N1P2b1/PqP3PP/7K w - - 0 1',
    solution: ['Rxe7', 'Qb1+', 'Nc1', 'Qxc1+', 'Qxc1'],
    hint: 'Rxe7 first! Then block check with Nc1, and finish with Qxc1!',
    hintVi: 'Xe ăn e7 trước! Sau đó chắn chiếu bằng Mã c1, và kết thúc bằng Hậu ăn c1!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p22_anastasia_pawn_storm',
    title: 'Level 22: Anastasia Pawn Storm 👑 (3 Moves)',
    titleVi: 'Cấp 22: Bão Tốt Tấn Cánh Vua 👑 (3 Nước)',
    description: 'Systematic 3-move pawn storm (f4 -> f5 -> f6) dismantling black King shelter!',
    descriptionVi: 'Chiến thuật đẩy Tốt liên tiếp (f4 -> f5 -> f6) phá vỡ tuyến phòng thủ Vua Đen!',
    fen: '5r1k/1p2N1pp/8/8/8/8/5PPP/5RK1 w - - 0 1',
    solution: ['f4', 'h6', 'f5', 'g5', 'f6'],
    hint: 'Push f-pawn step by step: f4, f5, then f6!',
    hintVi: 'Đẩy Tốt f từng bước: f4, f5, rồi f6!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p23_double_rook_invasion',
    title: 'Level 23: Double Rook 7th Rank Invasion 🏰 (3 Moves)',
    titleVi: 'Cấp 23: Song Xe Đột Nhập Hàng Cuối 🏰 (3 Nước)',
    description: 'Infiltrate enemy 7th rank with rooks in 3 decisive moves!',
    descriptionVi: 'Xâm nhập hàng cuối bằng đòn chiếu Xe d8!',
    fen: '6k1/5ppp/8/8/1r6/1P6/P1r2PPP/1R1R2K1 w - - 0 1',
    solution: ['Rd8#'],
    hint: 'Slide Rook to d8 for instant back-rank mate!',
    hintVi: 'Đẩy Xe lên d8 để chiếu hết hàng cuối!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p24_opera_house_queen_sac',
    title: 'Level 24: Opera House Queen Sacrifice 👸 (3 Moves)',
    titleVi: 'Cấp 24: Thí Hậu Kiểu Nhà Hát Opera 👸 (3 Nước)',
    description: 'Morphy-style Queen sacrifice on e8 opening the back-rank for Rook mate!',
    descriptionVi: 'Thí Hậu ở e8 theo phong cách Paul Morphy mở đường cho Xe chiếu hết!',
    fen: '4r1k1/ppp2ppp/8/8/8/8/PPP2PPP/3QR1K1 w - - 0 1',
    solution: ['Qxe8+', 'Rxe8', 'Rxe8#'],
    hint: 'Qxe8+ sacrifice opens up the enemy back-rank!',
    hintVi: 'Thí Hậu ăn e8+ mở toang hàng cuối!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p25_bodens_double_bishop',
    title: 'Level 25: Boden\'s Cross-Diagonal Attack ⚔️ (3 Moves)',
    titleVi: 'Cấp 25: Đòn Tượng Đôi Boden ⚔️ (3 Nước)',
    description: 'Execute a 3-move tactical sequence with central trade and bishop pressure!',
    descriptionVi: 'Thực hiện chuỗi đòn đổi quân trung tâm và gây sức ép bằng Tượng đôi!',
    fen: '2kr3r/pp1n1ppp/2p1p3/8/2B5/5B2/PPP2PPP/2KR4 w - - 0 1',
    solution: ['Bxd5', 'exd5', 'Rxd5'],
    hint: 'Bxd5 trade weakens central defense!',
    hintVi: 'Tượng ăn d5 làm suy yếu trung tâm!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p26_world_champ_endgame',
    title: 'Level 26: Grandmaster Active Rook Grind 🏆 (3 Moves)',
    titleVi: 'Cấp 26: Tàn Cuộc Xe Đại Kiện Tướng 🏆 (3 Nước)',
    description: 'Active King and Rook play in 3 moves forcing opponent passed pawn capture!',
    descriptionVi: 'Xe và Vua chủ động tấn công ăn Tốt a5 của đối phương!',
    fen: '8/8/8/p1k5/P7/8/2K5/1R6 w - - 0 1',
    solution: ['Rb5+', 'Kc6', 'Rxa5', 'Kb6', 'Rb5+'],
    hint: 'Rb5+ check, then capture black pawn on a5!',
    hintVi: 'Xe b5+ chiếu Vua, sau đó Xe ăn Tốt a5!',
    starsReward: 12,
    difficulty: 'Hard'
  },
  {
    id: 'p27_triple_battery_mate',
    title: 'Level 27: Triple Battery Back-Rank 🔋 (3 Moves)',
    titleVi: 'Cấp 27: Súng 3 Nòng Cột d 🔋 (3 Nước)',
    description: 'Unleash triple heavy piece battery along d-file!',
    descriptionVi: 'Kích hoạt hỏa lực hàng nặng trên cột d!',
    fen: '3r2k1/5ppp/8/8/8/8/3R1PPP/3Q2K1 w - - 0 1',
    solution: ['Rxd8+', 'Rxd8', 'Qxd8#'],
    hint: 'Rxd8+ followed by Qxd8#!',
    hintVi: 'Xe ăn d8+ tiếp theo Hậu ăn d8#!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p28_kingside_pawn_dismantle',
    title: 'Level 28: Kingside Shelter Dismantle 💣 (3 Moves)',
    titleVi: 'Cấp 28: Đột Nhập Hàng 7 Bằng Xe 💣 (3 Nước)',
    description: 'Crack open enemy kingside defense with a 3-move pawn lever!',
    descriptionVi: 'Đưa Xe xâm nhập hàng 7 để phá hủy hệ thống Tốt đối phương!',
    fen: '5rk1/ppp2ppp/8/3p4/3P4/5P2/PPP3PP/4R1K1 w - - 0 1',
    solution: ['Re7', 'Rc8', 'Rxc7'],
    hint: 'Re7 penetrates to 7th rank!',
    hintVi: 'Xe lên e7 xâm nhập hàng 7!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p29_smothered_mate_mastery',
    title: 'Level 29: Smothered Mate Mastery 🐴 (3 Moves)',
    titleVi: 'Cấp 29: Bậc Thầy Chiếu Nghẹt 🐴 (3 Nước)',
    description: 'Corner Black King with Knight jumping to f7!',
    descriptionVi: 'Dồn Vua Đen vào góc bằng đòn nhảy Mã f7 chiếu hết!',
    fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',
    solution: ['Nf7#'],
    hint: 'Nf7# delivers smothered checkmate!',
    hintVi: 'Mã f7# chiếu nghẹt Vua Đen!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p30_grandmaster_champ_combo',
    title: 'Level 30: Grandmaster Championship Combo 🔥 (3 Moves)',
    titleVi: 'Cấp 30: Đòn Kết Thúc Vô Địch 🔥 (3 Nước)',
    description: '3-move tactical checkmate crowning your puzzle journey!',
    descriptionVi: 'Đòn chiếu hết 3 nước hoàn thành chặng đường chinh phục Cờ Vua!',
    fen: '7k/2R5/8/8/8/8/8/1R4K1 w - - 0 1',
    solution: ['Rb8#'],
    hint: 'Rb8# finishes the game!',
    hintVi: 'Xe b8# kết thúc ván đấu!',
    starsReward: 12,
    difficulty: 'Hard'
  },

  // ==========================================
  // LEVEL 31 - 50: ADVANCED MASTER TACTICS
  // ==========================================
  {
    id: 'p31_corner_queen_mate',
    title: 'Level 31: Corner Queen Strike 👸 (1 Move)',
    titleVi: 'Cấp 31: Đòn Hậu Chiếu Hết Góc 👸 (1 Nước)',
    description: 'White King restricts enemy King while Queen delivers checkmate on g7!',
    descriptionVi: 'Vua Trắng khống chế Vua Đen trong khi Hậu ra đòn chiếu hết trên g7!',
    fen: '7k/5Q2/6K1/8/8/8/8/8 w - - 0 1',
    solution: ['Qg7#'],
    hint: 'Move Queen to g7 right next to enemy King!',
    hintVi: 'Di chuyển Hậu lên g7 ngay sát bên Vua Đen!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p32_back_rank_rook_strike',
    title: 'Level 32: Back-Rank Rook Strike 🚀 (1 Move)',
    titleVi: 'Cấp 32: Xe Băng Cột Hàng Cuối 🚀 (1 Nước)',
    description: 'Capture undefended Rook or slide to d8 for instant checkmate!',
    descriptionVi: 'Đẩy Xe xuống d8 ăn quân hoặc chiếu hết hàng cuối!',
    fen: '3r2k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1',
    solution: ['Rxd8#'],
    hint: 'Rook takes d8 checkmate!',
    hintVi: 'Dùng Xe ăn d8 chiếu hết!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p33_smothered_knight_g8',
    title: 'Level 33: Smothered Knight Check 🐴 (1 Move)',
    titleVi: 'Cấp 33: Mã Chiếu Nghẹt g8 🐴 (1 Nước)',
    description: 'Jump Knight to f7 for a classic smothered checkmate!',
    descriptionVi: 'Nhảy Mã lên f7 tạo thế chiếu nghẹt kinh điển!',
    fen: '6rk/5Npp/8/8/8/8/8/6K1 w - - 0 1',
    solution: ['Nf7#'],
    hint: 'Jump Knight to f7!',
    hintVi: 'Nhảy Mã lên ô f7!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p34_arabian_mate_1move',
    title: 'Level 34: Arabian Mate Power 🌙 (1 Move)',
    titleVi: 'Cấp 34: Đòn Chiếu Ả Rập (Xe & Mã) 🌙 (1 Nước)',
    description: 'Rook and Knight work together! Slide Rook to b8 for checkmate!',
    descriptionVi: 'Xe và Mã phối hợp nhịp nhàng! Đẩy Xe lên b8 để chiếu hết!',
    fen: '7k/7p/5N2/8/8/8/8/1R4K1 w - - 0 1',
    solution: ['Rb8#'],
    hint: 'Slide Rook to b8 guarded by Knight on f6!',
    hintVi: 'Đẩy Xe lên b8 dưới sự bảo vệ của Mã!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p35_queen_pin_skewer',
    title: 'Level 35: Queen Pin Skewer 📌 (1 Move)',
    titleVi: 'Cấp 35: Đòn Ghim Hậu Bắt Xe 📌 (1 Nước)',
    description: 'Pin the enemy Rook against the King with your Queen on d8!',
    descriptionVi: 'Ghim Xe đối phương chiếu Vua bằng cách phi Hậu lên d8!',
    fen: 'r3k2r/8/8/8/8/8/8/3Q2K1 w kq - 0 1',
    solution: ['Qd8+'],
    hint: 'Queen to d8 checks the King!',
    hintVi: 'Di chuyển Hậu lên d8 chiếu Vua!',
    starsReward: 3,
    difficulty: 'Easy'
  },
  {
    id: 'p36_queen_trade_simplification',
    title: 'Level 36: Queen Trade Simplification 👑 (2 Moves)',
    titleVi: 'Cấp 36: Đổi Hậu Chiếm Ưu Thế 👑 (2 Nước)',
    description: 'Trade queens on d5 to win material and simplify into an easy win!',
    descriptionVi: 'Đổi Hậu ở d5 để giành lợi thế quân số và tiến vào tàn cuộc thắng dễ dàng!',
    fen: 'r1b2rk1/ppp2ppp/2n5/3qp3/8/3P1Q2/PPP2PPP/R3K2R w KQ - 0 1',
    solution: ['Qxd5'],
    hint: 'Queen takes d5 wins Black Queen!',
    hintVi: 'Hậu ăn d5 tiêu diệt Hậu Đen!',
    starsReward: 5,
    difficulty: 'Medium'
  },
  {
    id: 'p37_royal_fork_c7',
    title: 'Level 37: Royal Fork Strike 🍴 (2 Moves)',
    titleVi: 'Cấp 37: Đòn Bắt Đôi Hoàng Gia c7 🍴 (2 Nước)',
    description: 'Jump Knight to c7 for a royal check and capture Black Rook on a8!',
    descriptionVi: 'Nhảy Mã vào c7 chiếu Vua và ăn Xe Đen ở a8!',
    fen: 'r3k2r/ppp2ppp/2n5/3N4/8/8/PPP2PPP/R3K2R w KQkq - 0 1',
    solution: ['Nxc7+', 'Ke7', 'Nxa8'],
    hint: 'Nxc7+ forks King and Rook!',
    hintVi: 'Mã ăn c7+ chiếu Vua và đe dọa Xe!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p38_back_rank_double_rook',
    title: 'Level 38: Double Rook Battery Back-Rank 🚀 (2 Moves)',
    titleVi: 'Cấp 38: Song Xe Băng Hàng Cuối 🚀 (2 Nước)',
    description: 'Sacrifice first Rook on d8 then finish with second Rook on d8#!',
    descriptionVi: 'Đưa Xe d8 chiếu trước, sau đó dùng Xe thứ hai lên d8# chiếu hết!',
    fen: '2r3k1/5ppp/8/8/8/8/3R1PPP/3R2K1 w - - 0 1',
    solution: ['Rd8+', 'Rxd8', 'Rxd8#'],
    hint: 'Rd8+ first, then Rxd8#!',
    hintVi: 'Xe d8+ trước, sau đó Xe ăn d8#!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p39_queen_interposition_mate',
    title: 'Level 39: Back-Rank Interposition 🎯 (2 Moves)',
    titleVi: 'Cấp 39: Chiếu Hết Hàng Cuối Chắn Quân 🎯 (2 Nước)',
    description: 'Check King with Qd8+, force Knight block, then capture Knight for mate!',
    descriptionVi: 'Chiếu Vua bằng Qd8+, buộc Mã cản, sau đó ăn Mã chiếu hết!',
    fen: '6k1/5ppp/5n2/8/8/5N2/5PPP/3Q2K1 w - - 0 1',
    solution: ['Qd8+', 'Ne8', 'Qxe8#'],
    hint: 'Qd8+ forces Knight to e8, then Qxe8#!',
    hintVi: 'Hậu d8+ buộc Mã lùi về e8, sau đó Hậu ăn e8#!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p40_bishop_pin_win',
    title: 'Level 40: Bishop Pin Attack 📌 (2 Moves)',
    titleVi: 'Cấp 40: Tượng Ghim Tấn Công Trung Tâm 📌 (2 Nước)',
    description: 'Push c3 pawn to kick Black Bishop back!',
    descriptionVi: 'Đẩy Tốt c3 để đẩy lùi Tượng Đen!',
    fen: 'r1bqk2r/pppp1ppp/2n5/4p3/1b2P3/3P1N2/PPP2PPP/R1BQKB1R w KQkq - 0 1',
    solution: ['c3', 'Ba5', 'b4'],
    hint: 'Push c3 to kick Black Bishop back!',
    hintVi: 'Đẩy Tốt c3 để đuổi Tượng Đen!',
    starsReward: 6,
    difficulty: 'Medium'
  },
  {
    id: 'p41_anastasia_knight_mate',
    title: 'Level 41: Anastasia Knight Rook Combo 🐴 (3 Moves)',
    titleVi: 'Cấp 41: Phối Hợp Xe & Mã Anastasia 🐴 (3 Nước)',
    description: 'Jump Knight to e7+, drive King to h8, then deliver back-rank checkmate!',
    descriptionVi: 'Nhảy Mã lên e7+, dồn Vua vào h8, sau đó chiếu hết hàng cuối!',
    fen: '5rk1/1p2N1pp/8/8/8/8/5PPP/1R4K1 w - - 0 1',
    solution: ['Nf5', 'g6', 'Rxb7'],
    hint: 'Activate Knight and Rook coordination!',
    hintVi: 'Phối hợp Mã và Xe tấn công cánh Vua!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p42_opera_queen_sacrifice',
    title: 'Level 42: Opera Queen Sacrifice Classic 👸 (3 Moves)',
    titleVi: 'Cấp 42: Thí Hậu Nhà Hát Opera Kinh Điển 👸 (3 Nước)',
    description: 'Qxe8+ sacrifice forces Black Rook capture, allowing Rxe8# checkmate!',
    descriptionVi: 'Thí Hậu Qxe8+ buộc Xe Đen ăn lại, tạo điều kiện cho Rxe8# chiếu hết!',
    fen: '4r1k1/ppp2ppp/8/8/8/8/PPP2PPP/3QR1K1 w - - 0 1',
    solution: ['Qxe8+', 'Rxe8', 'Rxe8#'],
    hint: 'Qxe8+ sacrifice opens up the entire rank!',
    hintVi: 'Thí Hậu Qxe8+ mở toang hàng cuối!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p43_triple_battery_d_file',
    title: 'Level 43: Triple Heavy Battery Strike 🔋 (3 Moves)',
    titleVi: 'Cấp 43: Hỏa Lực Ba Nòng Cột d 🔋 (3 Nước)',
    description: 'Overwhelm enemy back rank with sequential heavy piece sacrifices!',
    descriptionVi: 'Áp đảo hàng cuối đối phương bằng chuỗi tấn công dồn dập!',
    fen: '3r2k1/5ppp/8/8/8/8/3R1PPP/3R2K1 w - - 0 1',
    solution: ['Rxd8+', 'Rxd8', 'Rxd8#'],
    hint: 'Rxd8+ followed by Rxd8#!',
    hintVi: 'Xe ăn d8+ tiếp theo Xe ăn d8#!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p44_rook_seventh_rank_pawn_snip',
    title: 'Level 44: Rook 7th Rank Pawn Infiltration 🏰 (3 Moves)',
    titleVi: 'Cấp 44: Xe Đột Nhập Hàng 7 Bắt Tốt 🏰 (3 Nước)',
    description: 'Invade 7th rank with Re7, force defensive move, and snip c7 pawn!',
    descriptionVi: 'Xâm nhập hàng 7 bằng Re7, buộc đối phương phòng thủ và ăn Tốt c7!',
    fen: '5rk1/ppp2ppp/8/3p4/3P4/5P2/PPP3PP/4R1K1 w - - 0 1',
    solution: ['Re7', 'Rc8', 'Rxc7'],
    hint: 'Re7 penetrates to 7th rank!',
    hintVi: 'Xe lên e7 thâm nhập hàng 7!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p45_pawn_promotion_run_king',
    title: 'Level 45: Pawn Promotion Queen Checkmate 👑 (3 Moves)',
    titleVi: 'Cấp 45: Phong Hậu Tốt & Chiếu Hết 👑 (3 Nước)',
    description: 'Promote b7 pawn to Queen with check and deliver Qb2# checkmate on next move!',
    descriptionVi: 'Phong Tốt b7 thành Hậu kèm nước chiếu và dứt điểm Qb2# ở nước sau!',
    fen: '8/1P6/8/8/8/2K5/8/1k6 w - - 0 1',
    solution: ['b8=Q+', 'Ka2', 'Qb2#'],
    hint: 'b8=Q+ promotes with check, then Qb2#!',
    hintVi: 'Phong Hậu b8=Q+ chiếu Vua, sau đó Hậu b2#!',
    starsReward: 12,
    difficulty: 'Hard'
  },
  {
    id: 'p46_bishop_sacrifice_h7',
    title: 'Level 46: Greek Gift Sacrifice 🎁 (3 Moves)',
    titleVi: 'Cấp 46: Thí Tượng Món Quà Hy Lạp 🎁 (3 Nước)',
    description: 'Capture central knight on d5 with exd5!',
    descriptionVi: 'Tốt ăn Mã d5 giải phóng khu vực trung tâm!',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3np3/2B1P3/3P1N2/PPP2PPP/R1BQ1RK1 w - - 0 1',
    solution: ['exd5', 'Ne7', 'Re1'],
    hint: 'Capture central Knight on d5!',
    hintVi: 'Tốt ăn Mã d5!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p47_queen_knight_cooperation',
    title: 'Level 47: Queen & Knight Mate Combo 🐴 (3 Moves)',
    titleVi: 'Cấp 47: Hậu & Mã Tấn Công h7 🐴 (3 Nước)',
    description: 'Capture central pawn with Nxe5!',
    descriptionVi: 'Mã ăn e5 mở đường cho các quân cờTrắng!',
    fen: 'r1bq1rk1/ppp2ppp/2n5/4p3/8/2NP1N2/PPP1QPPP/R4RK1 w - - 0 1',
    solution: ['Nxe5', 'Nxe5', 'Qxe5'],
    hint: 'Nxe5 captures central pawn and opens queen path!',
    hintVi: 'Mã ăn e5 chiếm ưu thế trung tâm!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p48_king_rook_endgame_active',
    title: 'Level 48: Active King Rook Endgame Grind 🏆 (3 Moves)',
    titleVi: 'Cấp 48: Tàn Cuộc Xe & Vua Chủ Động 🏆 (3 Nước)',
    description: 'Use active Rook check to force enemy King away and capture passed pawn!',
    descriptionVi: 'Sử dụng Xe chiếu Vua đối phương và tiêu diệt Tốt thông!',
    fen: '8/8/8/p1k5/P7/8/2K5/1R6 w - - 0 1',
    solution: ['Rb5+', 'Kc6', 'Rxa5', 'Kb6', 'Rb5+'],
    hint: 'Rb5+ check then capture a5 pawn!',
    hintVi: 'Xe b5+ chiếu Vua, sau đó Xe ăn Tốt a5!',
    starsReward: 12,
    difficulty: 'Hard'
  },
  {
    id: 'p49_smothered_checkmate_pawn',
    title: 'Level 49: Smothered Mate Trap 🐴 (3 Moves)',
    titleVi: 'Cấp 49: Bẫy Chiếu Nghẹt Hoàn Hảo 🐴 (3 Nước)',
    description: 'Deliver smothered checkmate with Nf7# on trapped King!',
    descriptionVi: 'Thực hiện đòn chiếu nghẹt Nf7# lên Vua bị bao vây!',
    fen: '6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',
    solution: ['Nf7#'],
    hint: 'Nf7# finishes the game with smothered mate!',
    hintVi: 'Mã f7# chiếu nghẹt Vua Đen!',
    starsReward: 10,
    difficulty: 'Hard'
  },
  {
    id: 'p50_grandmaster_ladder_mate',
    title: 'Level 50: Championship Ladder Mate 🪜 (3 Moves)',
    titleVi: 'Cấp 50: Màn Lội Ngược Dòng Vô Địch 🪜 (3 Nước)',
    description: 'Complete level 50 with a glorious double Rook ladder checkmate!',
    descriptionVi: 'Hoàn thành Cấp 50 với màn chiếu hết hai Xe đỉnh cao!',
    fen: '7k/2R5/8/8/8/8/8/1R4K1 w - - 0 1',
    solution: ['Rb8#'],
    hint: 'Rb8# delivers checkmate!',
    hintVi: 'Xe b8# chiếu hết!',
    starsReward: 15,
    difficulty: 'Hard'
  }
];

// Qualification & Testing
const { qualified, rejectedCount } = qualifyPuzzleLibrary(RAW_KID_PUZZLES);

if (rejectedCount > 0) {
  console.warn(`[Puzzle Library Init] Filtered ${rejectedCount} non-qualifying puzzles out of ${RAW_KID_PUZZLES.length}.`);
}

export const KID_PUZZLES: Puzzle[] = qualified;
