import { BoardTheme, ThemeConfig } from '../types/chess';

export const BOARD_THEMES: Record<BoardTheme, ThemeConfig> = {
  duolingo: {
    id: 'duolingo',
    name: 'Duolingo Emerald 🦉',
    badge: 'Popular & Gamified',
    descriptionEn: 'Gamified emerald green board paired with vibrant 3D glass badge pieces.',
    descriptionVi: 'Bàn cờ xanh lục Emerald cùng bộ huy hiệu cờ 3D nổi bật tương phản cao.',
    lightSquare: 'bg-[#e2f7d8]',
    darkSquare: 'bg-[#58cc02]',
    highlightSelected: 'ring-4 ring-amber-300 bg-amber-200/80',
    highlightMove: 'bg-amber-400/60',
    highlightCheck: 'bg-rose-500/80 animate-pulse',
    bgGradient: 'from-emerald-950/40 via-green-900/30 to-slate-950',
    cardBg: 'bg-emerald-950/30 border-emerald-500/40',
    borderColor: 'border-emerald-500/50',
    textAccent: 'text-emerald-400',
    pieceStyle: 'duo_3d',
  },
  wood: {
    id: 'wood',
    name: 'Classic Wood 🪵',
    badge: 'Traditional Warmth',
    descriptionEn: 'Rich mahogany and birch wood board with warm hand-carved piece aesthetic.',
    descriptionVi: 'Bàn cờ gỗ bạch dương và sồi trầm ấm, cảm giác quân cờ khắc gỗ thủ công tinh tế.',
    lightSquare: 'bg-[#f0d9b5]',
    darkSquare: 'bg-[#b58863]',
    highlightSelected: 'ring-4 ring-amber-400 bg-amber-200/60',
    highlightMove: 'bg-emerald-400/50',
    highlightCheck: 'bg-rose-500/70 animate-pulse',
    bgGradient: 'from-amber-900/10 via-amber-800/10 to-amber-950/20',
    cardBg: 'bg-amber-950/20 border-amber-800/30',
    borderColor: 'border-amber-700/40',
    textAccent: 'text-amber-600',
    pieceStyle: 'wood_carved',
  },
  candy: {
    id: 'candy',
    name: 'Candy Kingdom 🍬',
    badge: 'Kid Favorite',
    descriptionEn: 'Playful pastel pink board with cute animal characters & royal emojis 🐴👑.',
    descriptionVi: 'Bàn cờ vương quốc kẹo ngọt rực rỡ cùng bộ linh vật đáng yêu dành cho trẻ em 🐴👑.',
    lightSquare: 'bg-[#fce7f3]',
    darkSquare: 'bg-[#f472b6]',
    highlightSelected: 'ring-4 ring-cyan-400 bg-pink-200',
    highlightMove: 'bg-teal-300/60',
    highlightCheck: 'bg-purple-600/80 animate-pulse',
    bgGradient: 'from-pink-100 via-purple-100 to-indigo-100 dark:from-pink-950/40 dark:to-purple-950/40',
    cardBg: 'bg-pink-900/10 border-pink-300/40',
    borderColor: 'border-pink-400/50',
    textAccent: 'text-pink-500',
    pieceStyle: 'cute_emoji',
  },
  space: {
    id: 'space',
    name: 'Cosmic Space 🚀',
    badge: 'Sleek & Futuristic',
    descriptionEn: 'Deep cosmic space indigo board with modern flat geometric piece silhouettes.',
    descriptionVi: 'Bàn cờ vũ trụ huyền bí kết hợp quân cờ phẳng tối giản hiện đại.',
    lightSquare: 'bg-[#e0e7ff]',
    darkSquare: 'bg-[#4f46e5]',
    highlightSelected: 'ring-4 ring-yellow-300 bg-indigo-300',
    highlightMove: 'bg-cyan-400/60',
    highlightCheck: 'bg-red-600/90 animate-pulse',
    bgGradient: 'from-slate-900 via-indigo-950 to-slate-950',
    cardBg: 'bg-indigo-950/40 border-indigo-700/50',
    borderColor: 'border-indigo-500/40',
    textAccent: 'text-indigo-400',
    pieceStyle: 'flat_minimal',
  },
  forest: {
    id: 'forest',
    name: 'Forest Adventure 🌿',
    badge: 'Tournament Standard',
    descriptionEn: 'Natural sage green forest board with high-contrast tournament-grade Staunton pieces.',
    descriptionVi: 'Bàn cờ rừng xanh dịu mắt cùng bộ cờ Staunton thi đấu tiêu chuẩn quốc tế.',
    lightSquare: 'bg-[#e9f5db]',
    darkSquare: 'bg-[#718355]',
    highlightSelected: 'ring-4 ring-yellow-400 bg-lime-200',
    highlightMove: 'bg-amber-300/60',
    highlightCheck: 'bg-red-500/80 animate-pulse',
    bgGradient: 'from-emerald-950/30 via-green-900/20 to-teal-950/30',
    cardBg: 'bg-emerald-900/20 border-emerald-700/40',
    borderColor: 'border-emerald-600/40',
    textAccent: 'text-emerald-500',
    pieceStyle: 'staunton',
  },
  neon: {
    id: 'neon',
    name: 'Neon Cyberpunk ⚡',
    badge: 'Arcade Glow',
    descriptionEn: 'Dark cyber slate board with cyan and purple neon glowing outline pieces.',
    descriptionVi: 'Bàn cờ Cyberpunk huyền ảo với quân cờ dạ quang phát sáng phong cách Gaming.',
    lightSquare: 'bg-[#334155]',
    darkSquare: 'bg-[#0f172a]',
    highlightSelected: 'ring-4 ring-cyan-400 bg-cyan-900/80',
    highlightMove: 'bg-fuchsia-500/60',
    highlightCheck: 'bg-rose-600/90 animate-pulse',
    bgGradient: 'from-slate-950 via-purple-950 to-slate-900',
    cardBg: 'bg-slate-900/80 border-cyan-500/30',
    borderColor: 'border-cyan-400/40',
    textAccent: 'text-cyan-400',
    pieceStyle: 'neon_cyber',
  },
};
